services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: one7
      MONGO_INITDB_ROOT_PASSWORD: one7mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: one7
      ME_CONFIG_MONGODB_ADMINPASSWORD: one7mongodb
      ME_CONFIG_MONGODB_URL: mongodb://one7:one7mongodb@mongo:27017/